repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        additional_dependencies: ['toml']
-   repo: https://github.com/ambv/black
    rev: v19.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.7.9
    hooks:
    -    id: flake8
         additional_dependencies: ['flake8-docstrings']